### ISSUE TITLE
Support for Orange Pi Lite

### ISSUE THREAD

**Issue by shaunmulligan** [linux-sunxi/meta-sunxi#181]
Hi I was wondering if it would be possible to add support for the Orange Pi Lite. Hardware wise its very, very similar to the already supported Orange Pi One. I started adding support in my fork (https://github.com/shaunmulligan/meta-sunxi/commit/8b3df5a3b1aa2baec7fa52d90cdd2581d08cb180) but I am wondering how to include the driver support for the built in Wifi chip on the board? Is there some preferred way of adding wifi driver/firmware to the BSP layer?

P.S. thanks for the awesome layer, I am using it to try add support for the sunxi boards on [resin.io](https://resin.io/)

**Comment by ebutera** [comment]
i don't know if there's a "standard" way but looking at meta-raspberry raspberrypi3.conf:

MACHINE_EXTRA_RRECOMMENDS += "linux-firmware-bcm43430"
KERNEL_DEFCONFIG ?= "bcm2709_defconfig"

of course replace bcm43430 with the one used in orange pi lite,  and i think you can create a orange-pi-lite_defconfig in meta-sunxi/recipes-kernel/linux/linux.

But instead of creating a custom defconfig you can add wifi support in the default defconfig, there are already many wifi modules enabled
